name: Build Kit-Proxy Adminstration User Interface

on:
    push:
        branches:
            - main
            - release/*
    pull_request:
        branches:
            - main
            - release/*

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 14.x

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Install dependencies using node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  
            - name: npm version
              run: npm -v

            - name: Install dependencies using npm and Node ${{ matrix.node-version }}
              run: npm install
              env:
                  NODE_VERSION: ${{ matrix.node-version }}
                  NODE_ENV: production

            - name: Build the application
              run: npm run build
              env:
                  NODE_VERSION: ${{ matrix.node-version }}
                  NODE_ENV: production

            # - name: Run tests
            #   run: npm run test
            #   env:
            #       NODE_VERSION: ${{ matrix.node-version }}
            #       NODE_ENV: production
